apiVersion: v1                    
kind: Namespace
metadata:
  name: cluster-hibernation                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-hibernation
  namespace: cluster-hibernation
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - cluster-hibernation
